const DATABASE_IDS = {
  WORKOUTS: process.env.WORKOUTS_DATABASE_ID, 
  BONUSES: process.env.BONUSES_DATABASE_ID,
  BALANCES: process.env.BALANCES_DATABASE_ID, 
  DEBT_CONTRACTS: process.env.DEBT_CONTRACTS_DATABASE_ID, 
  PUNISHMENTS: process.env.PUNISHMENTS_DATABASE_ID,
  MORNING_CHECKINS: process.env.MORNING_CHECKINS_DATABASE_ID, 
  SYSTEM_RULES: process.env.SYSTEM_RULES_DATABASE_ID 
};

module.exports = {
  DATABASE_IDS
};